// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/ringEOF.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RingEOF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Alive         []string               `protobuf:"bytes,2,rep,name=alive,proto3" json:"alive,omitempty"`
	Ready         []string               `protobuf:"bytes,3,rep,name=ready,proto3" json:"ready,omitempty"`
	CreatorId     string                 `protobuf:"bytes,4,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	EofType       string                 `protobuf:"bytes,5,opt,name=eofType,proto3" json:"eofType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RingEOF) Reset() {
	*x = RingEOF{}
	mi := &file_proto_ringEOF_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RingEOF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingEOF) ProtoMessage() {}

func (x *RingEOF) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ringEOF_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingEOF.ProtoReflect.Descriptor instead.
func (*RingEOF) Descriptor() ([]byte, []int) {
	return file_proto_ringEOF_proto_rawDescGZIP(), []int{0}
}

func (x *RingEOF) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *RingEOF) GetAlive() []string {
	if x != nil {
		return x.Alive
	}
	return nil
}

func (x *RingEOF) GetReady() []string {
	if x != nil {
		return x.Ready
	}
	return nil
}

func (x *RingEOF) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *RingEOF) GetEofType() string {
	if x != nil {
		return x.EofType
	}
	return ""
}

var File_proto_ringEOF_proto protoreflect.FileDescriptor

const file_proto_ringEOF_proto_rawDesc = "" +
	"\n" +
	"\x13proto/ringEOF.proto\"\x83\x01\n" +
	"\aRingEOF\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x14\n" +
	"\x05alive\x18\x02 \x03(\tR\x05alive\x12\x14\n" +
	"\x05ready\x18\x03 \x03(\tR\x05ready\x12\x1c\n" +
	"\tcreatorId\x18\x04 \x01(\tR\tcreatorId\x12\x18\n" +
	"\aeofType\x18\x05 \x01(\tR\aeofTypeB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_ringEOF_proto_rawDescOnce sync.Once
	file_proto_ringEOF_proto_rawDescData []byte
)

func file_proto_ringEOF_proto_rawDescGZIP() []byte {
	file_proto_ringEOF_proto_rawDescOnce.Do(func() {
		file_proto_ringEOF_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ringEOF_proto_rawDesc), len(file_proto_ringEOF_proto_rawDesc)))
	})
	return file_proto_ringEOF_proto_rawDescData
}

var file_proto_ringEOF_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_ringEOF_proto_goTypes = []any{
	(*RingEOF)(nil), // 0: RingEOF
}
var file_proto_ringEOF_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ringEOF_proto_init() }
func file_proto_ringEOF_proto_init() {
	if File_proto_ringEOF_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ringEOF_proto_rawDesc), len(file_proto_ringEOF_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ringEOF_proto_goTypes,
		DependencyIndexes: file_proto_ringEOF_proto_depIdxs,
		MessageInfos:      file_proto_ringEOF_proto_msgTypes,
	}.Build()
	File_proto_ringEOF_proto = out.File
	file_proto_ringEOF_proto_goTypes = nil
	file_proto_ringEOF_proto_depIdxs = nil
}
