// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/client-server-messages/server-to-client.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageStatus int32

const (
	MessageStatus_SUCCESS MessageStatus = 0
	MessageStatus_FAIL    MessageStatus = 1
	MessageStatus_PENDING MessageStatus = 2
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
		2: "PENDING",
	}
	MessageStatus_value = map[string]int32{
		"SUCCESS": 0,
		"FAIL":    1,
		"PENDING": 2,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_client_server_messages_server_to_client_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_proto_client_server_messages_server_to_client_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_client_server_messages_server_to_client_proto_rawDescGZIP(), []int{0}
}

type BatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Status        MessageStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=MessageStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAck) Reset() {
	*x = BatchAck{}
	mi := &file_proto_client_server_messages_server_to_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAck) ProtoMessage() {}

func (x *BatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_server_messages_server_to_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAck.ProtoReflect.Descriptor instead.
func (*BatchAck) Descriptor() ([]byte, []int) {
	return file_proto_client_server_messages_server_to_client_proto_rawDescGZIP(), []int{0}
}

func (x *BatchAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchAck) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_SUCCESS
}

type SyncAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAck) Reset() {
	*x = SyncAck{}
	mi := &file_proto_client_server_messages_server_to_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAck) ProtoMessage() {}

func (x *SyncAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_server_messages_server_to_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAck.ProtoReflect.Descriptor instead.
func (*SyncAck) Descriptor() ([]byte, []int) {
	return file_proto_client_server_messages_server_to_client_proto_rawDescGZIP(), []int{1}
}

func (x *SyncAck) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ResultResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        MessageStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=MessageStatus" json:"status,omitempty"`
	Responses     []*ResultResponse_Query `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_proto_client_server_messages_server_to_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_server_messages_server_to_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_server_messages_server_to_client_proto_rawDescGZIP(), []int{2}
}

func (x *ResultResponse) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_SUCCESS
}

func (x *ResultResponse) GetResponses() []*ResultResponse_Query {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ServerClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerClientMessage_BatchAck
	//	*ServerClientMessage_SyncAck
	//	*ServerClientMessage_Request
	Message       isServerClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerClientMessage) Reset() {
	*x = ServerClientMessage{}
	mi := &file_proto_client_server_messages_server_to_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerClientMessage) ProtoMessage() {}

func (x *ServerClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_server_messages_server_to_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerClientMessage.ProtoReflect.Descriptor instead.
func (*ServerClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_client_server_messages_server_to_client_proto_rawDescGZIP(), []int{3}
}

func (x *ServerClientMessage) GetMessage() isServerClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerClientMessage) GetBatchAck() *BatchAck {
	if x != nil {
		if x, ok := x.Message.(*ServerClientMessage_BatchAck); ok {
			return x.BatchAck
		}
	}
	return nil
}

func (x *ServerClientMessage) GetSyncAck() *SyncAck {
	if x != nil {
		if x, ok := x.Message.(*ServerClientMessage_SyncAck); ok {
			return x.SyncAck
		}
	}
	return nil
}

func (x *ServerClientMessage) GetRequest() *ResultResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerClientMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

type isServerClientMessage_Message interface {
	isServerClientMessage_Message()
}

type ServerClientMessage_BatchAck struct {
	BatchAck *BatchAck `protobuf:"bytes,1,opt,name=batch_ack,json=batchAck,proto3,oneof"`
}

type ServerClientMessage_SyncAck struct {
	SyncAck *SyncAck `protobuf:"bytes,2,opt,name=sync_ack,json=syncAck,proto3,oneof"`
}

type ServerClientMessage_Request struct {
	Request *ResultResponse `protobuf:"bytes,3,opt,name=request,proto3,oneof"`
}

func (*ServerClientMessage_BatchAck) isServerClientMessage_Message() {}

func (*ServerClientMessage_SyncAck) isServerClientMessage_Message() {}

func (*ServerClientMessage_Request) isServerClientMessage_Message() {}

type ResultResponse_Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ResultResponse_Query_Result1
	//	*ResultResponse_Query_Result2
	//	*ResultResponse_Query_Result3
	//	*ResultResponse_Query_Result4
	//	*ResultResponse_Query_Result5
	Message       isResultResponse_Query_Message `protobuf_oneof:"Message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse_Query) Reset() {
	*x = ResultResponse_Query{}
	mi := &file_proto_client_server_messages_server_to_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse_Query) ProtoMessage() {}

func (x *ResultResponse_Query) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_server_messages_server_to_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse_Query.ProtoReflect.Descriptor instead.
func (*ResultResponse_Query) Descriptor() ([]byte, []int) {
	return file_proto_client_server_messages_server_to_client_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ResultResponse_Query) GetMessage() isResultResponse_Query_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ResultResponse_Query) GetResult1() *Result1 {
	if x != nil {
		if x, ok := x.Message.(*ResultResponse_Query_Result1); ok {
			return x.Result1
		}
	}
	return nil
}

func (x *ResultResponse_Query) GetResult2() *Result2 {
	if x != nil {
		if x, ok := x.Message.(*ResultResponse_Query_Result2); ok {
			return x.Result2
		}
	}
	return nil
}

func (x *ResultResponse_Query) GetResult3() *Result3 {
	if x != nil {
		if x, ok := x.Message.(*ResultResponse_Query_Result3); ok {
			return x.Result3
		}
	}
	return nil
}

func (x *ResultResponse_Query) GetResult4() *Result4 {
	if x != nil {
		if x, ok := x.Message.(*ResultResponse_Query_Result4); ok {
			return x.Result4
		}
	}
	return nil
}

func (x *ResultResponse_Query) GetResult5() *Result5 {
	if x != nil {
		if x, ok := x.Message.(*ResultResponse_Query_Result5); ok {
			return x.Result5
		}
	}
	return nil
}

type isResultResponse_Query_Message interface {
	isResultResponse_Query_Message()
}

type ResultResponse_Query_Result1 struct {
	Result1 *Result1 `protobuf:"bytes,1,opt,name=result1,proto3,oneof"`
}

type ResultResponse_Query_Result2 struct {
	Result2 *Result2 `protobuf:"bytes,2,opt,name=result2,proto3,oneof"`
}

type ResultResponse_Query_Result3 struct {
	Result3 *Result3 `protobuf:"bytes,3,opt,name=result3,proto3,oneof"`
}

type ResultResponse_Query_Result4 struct {
	Result4 *Result4 `protobuf:"bytes,4,opt,name=result4,proto3,oneof"`
}

type ResultResponse_Query_Result5 struct {
	Result5 *Result5 `protobuf:"bytes,5,opt,name=result5,proto3,oneof"`
}

func (*ResultResponse_Query_Result1) isResultResponse_Query_Message() {}

func (*ResultResponse_Query_Result2) isResultResponse_Query_Message() {}

func (*ResultResponse_Query_Result3) isResultResponse_Query_Message() {}

func (*ResultResponse_Query_Result4) isResultResponse_Query_Message() {}

func (*ResultResponse_Query_Result5) isResultResponse_Query_Message() {}

var File_proto_client_server_messages_server_to_client_proto protoreflect.FileDescriptor

const file_proto_client_server_messages_server_to_client_proto_rawDesc = "" +
	"\n" +
	"3proto/client-server-messages/server-to-client.proto\x1a\x1aproto/stages/result1.proto\x1a\x1aproto/stages/result2.proto\x1a\x1aproto/stages/result3.proto\x1a\x1aproto/stages/result4.proto\x1a\x1aproto/stages/result5.proto\"M\n" +
	"\bBatchAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.MessageStatusR\x06status\"&\n" +
	"\aSyncAck\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xc0\x02\n" +
	"\x0eResultResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.MessageStatusR\x06status\x123\n" +
	"\tresponses\x18\x02 \x03(\v2\x15.ResultResponse.QueryR\tresponses\x1a\xd0\x01\n" +
	"\x05Query\x12$\n" +
	"\aresult1\x18\x01 \x01(\v2\b.Result1H\x00R\aresult1\x12$\n" +
	"\aresult2\x18\x02 \x01(\v2\b.Result2H\x00R\aresult2\x12$\n" +
	"\aresult3\x18\x03 \x01(\v2\b.Result3H\x00R\aresult3\x12$\n" +
	"\aresult4\x18\x04 \x01(\v2\b.Result4H\x00R\aresult4\x12$\n" +
	"\aresult5\x18\x05 \x01(\v2\b.Result5H\x00R\aresult5B\t\n" +
	"\aMessage\"\x9e\x01\n" +
	"\x13ServerClientMessage\x12(\n" +
	"\tbatch_ack\x18\x01 \x01(\v2\t.BatchAckH\x00R\bbatchAck\x12%\n" +
	"\bsync_ack\x18\x02 \x01(\v2\b.SyncAckH\x00R\asyncAck\x12+\n" +
	"\arequest\x18\x03 \x01(\v2\x0f.ResultResponseH\x00R\arequestB\t\n" +
	"\amessage*3\n" +
	"\rMessageStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02B\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_client_server_messages_server_to_client_proto_rawDescOnce sync.Once
	file_proto_client_server_messages_server_to_client_proto_rawDescData []byte
)

func file_proto_client_server_messages_server_to_client_proto_rawDescGZIP() []byte {
	file_proto_client_server_messages_server_to_client_proto_rawDescOnce.Do(func() {
		file_proto_client_server_messages_server_to_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_server_messages_server_to_client_proto_rawDesc), len(file_proto_client_server_messages_server_to_client_proto_rawDesc)))
	})
	return file_proto_client_server_messages_server_to_client_proto_rawDescData
}

var file_proto_client_server_messages_server_to_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_client_server_messages_server_to_client_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_client_server_messages_server_to_client_proto_goTypes = []any{
	(MessageStatus)(0),           // 0: MessageStatus
	(*BatchAck)(nil),             // 1: BatchAck
	(*SyncAck)(nil),              // 2: SyncAck
	(*ResultResponse)(nil),       // 3: ResultResponse
	(*ServerClientMessage)(nil),  // 4: ServerClientMessage
	(*ResultResponse_Query)(nil), // 5: ResultResponse.Query
	(*Result1)(nil),              // 6: Result1
	(*Result2)(nil),              // 7: Result2
	(*Result3)(nil),              // 8: Result3
	(*Result4)(nil),              // 9: Result4
	(*Result5)(nil),              // 10: Result5
}
var file_proto_client_server_messages_server_to_client_proto_depIdxs = []int32{
	0,  // 0: BatchAck.status:type_name -> MessageStatus
	0,  // 1: ResultResponse.status:type_name -> MessageStatus
	5,  // 2: ResultResponse.responses:type_name -> ResultResponse.Query
	1,  // 3: ServerClientMessage.batch_ack:type_name -> BatchAck
	2,  // 4: ServerClientMessage.sync_ack:type_name -> SyncAck
	3,  // 5: ServerClientMessage.request:type_name -> ResultResponse
	6,  // 6: ResultResponse.Query.result1:type_name -> Result1
	7,  // 7: ResultResponse.Query.result2:type_name -> Result2
	8,  // 8: ResultResponse.Query.result3:type_name -> Result3
	9,  // 9: ResultResponse.Query.result4:type_name -> Result4
	10, // 10: ResultResponse.Query.result5:type_name -> Result5
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_client_server_messages_server_to_client_proto_init() }
func file_proto_client_server_messages_server_to_client_proto_init() {
	if File_proto_client_server_messages_server_to_client_proto != nil {
		return
	}
	file_proto_stages_result1_proto_init()
	file_proto_stages_result2_proto_init()
	file_proto_stages_result3_proto_init()
	file_proto_stages_result4_proto_init()
	file_proto_stages_result5_proto_init()
	file_proto_client_server_messages_server_to_client_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerClientMessage_BatchAck)(nil),
		(*ServerClientMessage_SyncAck)(nil),
		(*ServerClientMessage_Request)(nil),
	}
	file_proto_client_server_messages_server_to_client_proto_msgTypes[4].OneofWrappers = []any{
		(*ResultResponse_Query_Result1)(nil),
		(*ResultResponse_Query_Result2)(nil),
		(*ResultResponse_Query_Result3)(nil),
		(*ResultResponse_Query_Result4)(nil),
		(*ResultResponse_Query_Result5)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_server_messages_server_to_client_proto_rawDesc), len(file_proto_client_server_messages_server_to_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_client_server_messages_server_to_client_proto_goTypes,
		DependencyIndexes: file_proto_client_server_messages_server_to_client_proto_depIdxs,
		EnumInfos:         file_proto_client_server_messages_server_to_client_proto_enumTypes,
		MessageInfos:      file_proto_client_server_messages_server_to_client_proto_msgTypes,
	}.Build()
	File_proto_client_server_messages_server_to_client_proto = out.File
	file_proto_client_server_messages_server_to_client_proto_goTypes = nil
	file_proto_client_server_messages_server_to_client_proto_depIdxs = nil
}
