// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/task.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Stage:
	//
	//	*Task_Alpha
	//	*Task_Beta
	//	*Task_Gamma
	//	*Task_Delta
	//	*Task_Epsilon
	//	*Task_Zeta
	//	*Task_Eta
	//	*Task_Theta
	//	*Task_Iota
	//	*Task_Kappa
	//	*Task_Lambda
	//	*Task_Mu
	//	*Task_Nu
	//	*Task_Result1
	//	*Task_Result2
	//	*Task_Result3
	//	*Task_Result4
	//	*Task_Result5
	Stage         isTask_Stage `protobuf_oneof:"Stage"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetStage() isTask_Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *Task) GetAlpha() *Alpha {
	if x != nil {
		if x, ok := x.Stage.(*Task_Alpha); ok {
			return x.Alpha
		}
	}
	return nil
}

func (x *Task) GetBeta() *Beta {
	if x != nil {
		if x, ok := x.Stage.(*Task_Beta); ok {
			return x.Beta
		}
	}
	return nil
}

func (x *Task) GetGamma() *Gamma {
	if x != nil {
		if x, ok := x.Stage.(*Task_Gamma); ok {
			return x.Gamma
		}
	}
	return nil
}

func (x *Task) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Stage.(*Task_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *Task) GetEpsilon() *Epsilon {
	if x != nil {
		if x, ok := x.Stage.(*Task_Epsilon); ok {
			return x.Epsilon
		}
	}
	return nil
}

func (x *Task) GetZeta() *Zeta {
	if x != nil {
		if x, ok := x.Stage.(*Task_Zeta); ok {
			return x.Zeta
		}
	}
	return nil
}

func (x *Task) GetEta() *Eta {
	if x != nil {
		if x, ok := x.Stage.(*Task_Eta); ok {
			return x.Eta
		}
	}
	return nil
}

func (x *Task) GetTheta() *Theta {
	if x != nil {
		if x, ok := x.Stage.(*Task_Theta); ok {
			return x.Theta
		}
	}
	return nil
}

func (x *Task) GetIota() *Iota {
	if x != nil {
		if x, ok := x.Stage.(*Task_Iota); ok {
			return x.Iota
		}
	}
	return nil
}

func (x *Task) GetKappa() *Kappa {
	if x != nil {
		if x, ok := x.Stage.(*Task_Kappa); ok {
			return x.Kappa
		}
	}
	return nil
}

func (x *Task) GetLambda() *Lambda {
	if x != nil {
		if x, ok := x.Stage.(*Task_Lambda); ok {
			return x.Lambda
		}
	}
	return nil
}

func (x *Task) GetMu() *Mu {
	if x != nil {
		if x, ok := x.Stage.(*Task_Mu); ok {
			return x.Mu
		}
	}
	return nil
}

func (x *Task) GetNu() *Nu {
	if x != nil {
		if x, ok := x.Stage.(*Task_Nu); ok {
			return x.Nu
		}
	}
	return nil
}

func (x *Task) GetResult1() *Result1 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Result1); ok {
			return x.Result1
		}
	}
	return nil
}

func (x *Task) GetResult2() *Result2 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Result2); ok {
			return x.Result2
		}
	}
	return nil
}

func (x *Task) GetResult3() *Result3 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Result3); ok {
			return x.Result3
		}
	}
	return nil
}

func (x *Task) GetResult4() *Result4 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Result4); ok {
			return x.Result4
		}
	}
	return nil
}

func (x *Task) GetResult5() *Result5 {
	if x != nil {
		if x, ok := x.Stage.(*Task_Result5); ok {
			return x.Result5
		}
	}
	return nil
}

type isTask_Stage interface {
	isTask_Stage()
}

type Task_Alpha struct {
	Alpha *Alpha `protobuf:"bytes,1,opt,name=alpha,proto3,oneof"`
}

type Task_Beta struct {
	Beta *Beta `protobuf:"bytes,2,opt,name=beta,proto3,oneof"`
}

type Task_Gamma struct {
	Gamma *Gamma `protobuf:"bytes,3,opt,name=gamma,proto3,oneof"`
}

type Task_Delta struct {
	Delta *Delta `protobuf:"bytes,4,opt,name=delta,proto3,oneof"`
}

type Task_Epsilon struct {
	Epsilon *Epsilon `protobuf:"bytes,5,opt,name=epsilon,proto3,oneof"`
}

type Task_Zeta struct {
	Zeta *Zeta `protobuf:"bytes,6,opt,name=zeta,proto3,oneof"`
}

type Task_Eta struct {
	Eta *Eta `protobuf:"bytes,7,opt,name=eta,proto3,oneof"`
}

type Task_Theta struct {
	Theta *Theta `protobuf:"bytes,8,opt,name=theta,proto3,oneof"`
}

type Task_Iota struct {
	Iota *Iota `protobuf:"bytes,9,opt,name=iota,proto3,oneof"`
}

type Task_Kappa struct {
	Kappa *Kappa `protobuf:"bytes,10,opt,name=kappa,proto3,oneof"`
}

type Task_Lambda struct {
	Lambda *Lambda `protobuf:"bytes,11,opt,name=lambda,proto3,oneof"`
}

type Task_Mu struct {
	Mu *Mu `protobuf:"bytes,12,opt,name=mu,proto3,oneof"`
}

type Task_Nu struct {
	Nu *Nu `protobuf:"bytes,13,opt,name=nu,proto3,oneof"`
}

type Task_Result1 struct {
	Result1 *Result1 `protobuf:"bytes,14,opt,name=result1,proto3,oneof"`
}

type Task_Result2 struct {
	Result2 *Result2 `protobuf:"bytes,15,opt,name=result2,proto3,oneof"`
}

type Task_Result3 struct {
	Result3 *Result3 `protobuf:"bytes,16,opt,name=result3,proto3,oneof"`
}

type Task_Result4 struct {
	Result4 *Result4 `protobuf:"bytes,17,opt,name=result4,proto3,oneof"`
}

type Task_Result5 struct {
	Result5 *Result5 `protobuf:"bytes,18,opt,name=result5,proto3,oneof"`
}

func (*Task_Alpha) isTask_Stage() {}

func (*Task_Beta) isTask_Stage() {}

func (*Task_Gamma) isTask_Stage() {}

func (*Task_Delta) isTask_Stage() {}

func (*Task_Epsilon) isTask_Stage() {}

func (*Task_Zeta) isTask_Stage() {}

func (*Task_Eta) isTask_Stage() {}

func (*Task_Theta) isTask_Stage() {}

func (*Task_Iota) isTask_Stage() {}

func (*Task_Kappa) isTask_Stage() {}

func (*Task_Lambda) isTask_Stage() {}

func (*Task_Mu) isTask_Stage() {}

func (*Task_Nu) isTask_Stage() {}

func (*Task_Result1) isTask_Stage() {}

func (*Task_Result2) isTask_Stage() {}

func (*Task_Result3) isTask_Stage() {}

func (*Task_Result4) isTask_Stage() {}

func (*Task_Result5) isTask_Stage() {}

var File_proto_task_proto protoreflect.FileDescriptor

const file_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x10proto/task.proto\x1a\x18proto/stages/alpha.proto\x1a\x17proto/stages/beta.proto\x1a\x18proto/stages/gamma.proto\x1a\x18proto/stages/delta.proto\x1a\x1aproto/stages/epsilon.proto\x1a\x17proto/stages/zeta.proto\x1a\x16proto/stages/eta.proto\x1a\x18proto/stages/theta.proto\x1a\x17proto/stages/iota.proto\x1a\x18proto/stages/kappa.proto\x1a\x19proto/stages/lambda.proto\x1a\x15proto/stages/mu.proto\x1a\x15proto/stages/nu.proto\x1a\x1aproto/stages/result1.proto\x1a\x1aproto/stages/result2.proto\x1a\x1aproto/stages/result3.proto\x1a\x1aproto/stages/result4.proto\x1a\x1aproto/stages/result5.proto\"\xd5\x04\n" +
	"\x04Task\x12\x1e\n" +
	"\x05alpha\x18\x01 \x01(\v2\x06.AlphaH\x00R\x05alpha\x12\x1b\n" +
	"\x04beta\x18\x02 \x01(\v2\x05.BetaH\x00R\x04beta\x12\x1e\n" +
	"\x05gamma\x18\x03 \x01(\v2\x06.GammaH\x00R\x05gamma\x12\x1e\n" +
	"\x05delta\x18\x04 \x01(\v2\x06.DeltaH\x00R\x05delta\x12$\n" +
	"\aepsilon\x18\x05 \x01(\v2\b.EpsilonH\x00R\aepsilon\x12\x1b\n" +
	"\x04zeta\x18\x06 \x01(\v2\x05.ZetaH\x00R\x04zeta\x12\x18\n" +
	"\x03eta\x18\a \x01(\v2\x04.EtaH\x00R\x03eta\x12\x1e\n" +
	"\x05theta\x18\b \x01(\v2\x06.ThetaH\x00R\x05theta\x12\x1b\n" +
	"\x04iota\x18\t \x01(\v2\x05.IotaH\x00R\x04iota\x12\x1e\n" +
	"\x05kappa\x18\n" +
	" \x01(\v2\x06.KappaH\x00R\x05kappa\x12!\n" +
	"\x06lambda\x18\v \x01(\v2\a.LambdaH\x00R\x06lambda\x12\x15\n" +
	"\x02mu\x18\f \x01(\v2\x03.MuH\x00R\x02mu\x12\x15\n" +
	"\x02nu\x18\r \x01(\v2\x03.NuH\x00R\x02nu\x12$\n" +
	"\aresult1\x18\x0e \x01(\v2\b.Result1H\x00R\aresult1\x12$\n" +
	"\aresult2\x18\x0f \x01(\v2\b.Result2H\x00R\aresult2\x12$\n" +
	"\aresult3\x18\x10 \x01(\v2\b.Result3H\x00R\aresult3\x12$\n" +
	"\aresult4\x18\x11 \x01(\v2\b.Result4H\x00R\aresult4\x12$\n" +
	"\aresult5\x18\x12 \x01(\v2\b.Result5H\x00R\aresult5B\a\n" +
	"\x05StageB\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_task_proto_rawDescOnce sync.Once
	file_proto_task_proto_rawDescData []byte
)

func file_proto_task_proto_rawDescGZIP() []byte {
	file_proto_task_proto_rawDescOnce.Do(func() {
		file_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)))
	})
	return file_proto_task_proto_rawDescData
}

var file_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_task_proto_goTypes = []any{
	(*Task)(nil),    // 0: Task
	(*Alpha)(nil),   // 1: Alpha
	(*Beta)(nil),    // 2: Beta
	(*Gamma)(nil),   // 3: Gamma
	(*Delta)(nil),   // 4: Delta
	(*Epsilon)(nil), // 5: Epsilon
	(*Zeta)(nil),    // 6: Zeta
	(*Eta)(nil),     // 7: Eta
	(*Theta)(nil),   // 8: Theta
	(*Iota)(nil),    // 9: Iota
	(*Kappa)(nil),   // 10: Kappa
	(*Lambda)(nil),  // 11: Lambda
	(*Mu)(nil),      // 12: Mu
	(*Nu)(nil),      // 13: Nu
	(*Result1)(nil), // 14: Result1
	(*Result2)(nil), // 15: Result2
	(*Result3)(nil), // 16: Result3
	(*Result4)(nil), // 17: Result4
	(*Result5)(nil), // 18: Result5
}
var file_proto_task_proto_depIdxs = []int32{
	1,  // 0: Task.alpha:type_name -> Alpha
	2,  // 1: Task.beta:type_name -> Beta
	3,  // 2: Task.gamma:type_name -> Gamma
	4,  // 3: Task.delta:type_name -> Delta
	5,  // 4: Task.epsilon:type_name -> Epsilon
	6,  // 5: Task.zeta:type_name -> Zeta
	7,  // 6: Task.eta:type_name -> Eta
	8,  // 7: Task.theta:type_name -> Theta
	9,  // 8: Task.iota:type_name -> Iota
	10, // 9: Task.kappa:type_name -> Kappa
	11, // 10: Task.lambda:type_name -> Lambda
	12, // 11: Task.mu:type_name -> Mu
	13, // 12: Task.nu:type_name -> Nu
	14, // 13: Task.result1:type_name -> Result1
	15, // 14: Task.result2:type_name -> Result2
	16, // 15: Task.result3:type_name -> Result3
	17, // 16: Task.result4:type_name -> Result4
	18, // 17: Task.result5:type_name -> Result5
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_task_proto_init() }
func file_proto_task_proto_init() {
	if File_proto_task_proto != nil {
		return
	}
	file_proto_stages_alpha_proto_init()
	file_proto_stages_beta_proto_init()
	file_proto_stages_gamma_proto_init()
	file_proto_stages_delta_proto_init()
	file_proto_stages_epsilon_proto_init()
	file_proto_stages_zeta_proto_init()
	file_proto_stages_eta_proto_init()
	file_proto_stages_theta_proto_init()
	file_proto_stages_iota_proto_init()
	file_proto_stages_kappa_proto_init()
	file_proto_stages_lambda_proto_init()
	file_proto_stages_mu_proto_init()
	file_proto_stages_nu_proto_init()
	file_proto_stages_result1_proto_init()
	file_proto_stages_result2_proto_init()
	file_proto_stages_result3_proto_init()
	file_proto_stages_result4_proto_init()
	file_proto_stages_result5_proto_init()
	file_proto_task_proto_msgTypes[0].OneofWrappers = []any{
		(*Task_Alpha)(nil),
		(*Task_Beta)(nil),
		(*Task_Gamma)(nil),
		(*Task_Delta)(nil),
		(*Task_Epsilon)(nil),
		(*Task_Zeta)(nil),
		(*Task_Eta)(nil),
		(*Task_Theta)(nil),
		(*Task_Iota)(nil),
		(*Task_Kappa)(nil),
		(*Task_Lambda)(nil),
		(*Task_Mu)(nil),
		(*Task_Nu)(nil),
		(*Task_Result1)(nil),
		(*Task_Result2)(nil),
		(*Task_Result3)(nil),
		(*Task_Result4)(nil),
		(*Task_Result5)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_task_proto_goTypes,
		DependencyIndexes: file_proto_task_proto_depIdxs,
		MessageInfos:      file_proto_task_proto_msgTypes,
	}.Build()
	File_proto_task_proto = out.File
	file_proto_task_proto_goTypes = nil
	file_proto_task_proto_depIdxs = nil
}
