// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/task.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryStage int32

const (
	QueryStage_UNASSIGNED QueryStage = 0
)

// Enum value maps for QueryStage.
var (
	QueryStage_name = map[int32]string{
		0: "UNASSIGNED",
	}
	QueryStage_value = map[string]int32{
		"UNASSIGNED": 0,
	}
)

func (x QueryStage) Enum() *QueryStage {
	p := new(QueryStage)
	*p = x
	return p
}

func (x QueryStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryStage) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_proto_enumTypes[0].Descriptor()
}

func (QueryStage) Type() protoreflect.EnumType {
	return &file_proto_task_proto_enumTypes[0]
}

func (x QueryStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryStage.Descriptor instead.
func (QueryStage) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

type DataRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*DataRow_Movie
	//	*DataRow_Credit
	//	*DataRow_Rating
	Data          isDataRow_Data `protobuf_oneof:"Data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRow) Reset() {
	*x = DataRow{}
	mi := &file_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRow) ProtoMessage() {}

func (x *DataRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRow.ProtoReflect.Descriptor instead.
func (*DataRow) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *DataRow) GetData() isDataRow_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataRow) GetMovie() *Movie {
	if x != nil {
		if x, ok := x.Data.(*DataRow_Movie); ok {
			return x.Movie
		}
	}
	return nil
}

func (x *DataRow) GetCredit() *Credit {
	if x != nil {
		if x, ok := x.Data.(*DataRow_Credit); ok {
			return x.Credit
		}
	}
	return nil
}

func (x *DataRow) GetRating() *Rating {
	if x != nil {
		if x, ok := x.Data.(*DataRow_Rating); ok {
			return x.Rating
		}
	}
	return nil
}

type isDataRow_Data interface {
	isDataRow_Data()
}

type DataRow_Movie struct {
	Movie *Movie `protobuf:"bytes,2,opt,name=movie,proto3,oneof"`
}

type DataRow_Credit struct {
	Credit *Credit `protobuf:"bytes,3,opt,name=credit,proto3,oneof"`
}

type DataRow_Rating struct {
	Rating *Rating `protobuf:"bytes,4,opt,name=rating,proto3,oneof"`
}

func (*DataRow_Movie) isDataRow_Data() {}

func (*DataRow_Credit) isDataRow_Data() {}

func (*DataRow_Rating) isDataRow_Data() {}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         QueryStage             `protobuf:"varint,1,opt,name=stage,proto3,enum=QueryStage" json:"stage,omitempty"`
	Data          []*DataRow             `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetStage() QueryStage {
	if x != nil {
		return x.Stage
	}
	return QueryStage_UNASSIGNED
}

func (x *Task) GetData() []*DataRow {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_task_proto protoreflect.FileDescriptor

const file_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x10proto/task.proto\x1a\x11proto/movie.proto\x1a\x12proto/credit.proto\x1a\x12proto/rating.proto\"w\n" +
	"\aDataRow\x12\x1e\n" +
	"\x05movie\x18\x02 \x01(\v2\x06.MovieH\x00R\x05movie\x12!\n" +
	"\x06credit\x18\x03 \x01(\v2\a.CreditH\x00R\x06credit\x12!\n" +
	"\x06rating\x18\x04 \x01(\v2\a.RatingH\x00R\x06ratingB\x06\n" +
	"\x04Data\"G\n" +
	"\x04Task\x12!\n" +
	"\x05stage\x18\x01 \x01(\x0e2\v.QueryStageR\x05stage\x12\x1c\n" +
	"\x04data\x18\x02 \x03(\v2\b.DataRowR\x04data*\x1c\n" +
	"\n" +
	"QueryStage\x12\x0e\n" +
	"\n" +
	"UNASSIGNED\x10\x00B\x1fZ\x1dcommon/communication/protocolb\x06proto3"

var (
	file_proto_task_proto_rawDescOnce sync.Once
	file_proto_task_proto_rawDescData []byte
)

func file_proto_task_proto_rawDescGZIP() []byte {
	file_proto_task_proto_rawDescOnce.Do(func() {
		file_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)))
	})
	return file_proto_task_proto_rawDescData
}

var file_proto_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_task_proto_goTypes = []any{
	(QueryStage)(0), // 0: QueryStage
	(*DataRow)(nil), // 1: DataRow
	(*Task)(nil),    // 2: Task
	(*Movie)(nil),   // 3: Movie
	(*Credit)(nil),  // 4: Credit
	(*Rating)(nil),  // 5: Rating
}
var file_proto_task_proto_depIdxs = []int32{
	3, // 0: DataRow.movie:type_name -> Movie
	4, // 1: DataRow.credit:type_name -> Credit
	5, // 2: DataRow.rating:type_name -> Rating
	0, // 3: Task.stage:type_name -> QueryStage
	1, // 4: Task.data:type_name -> DataRow
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_task_proto_init() }
func file_proto_task_proto_init() {
	if File_proto_task_proto != nil {
		return
	}
	file_proto_movie_proto_init()
	file_proto_credit_proto_init()
	file_proto_rating_proto_init()
	file_proto_task_proto_msgTypes[0].OneofWrappers = []any{
		(*DataRow_Movie)(nil),
		(*DataRow_Credit)(nil),
		(*DataRow_Rating)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_task_proto_goTypes,
		DependencyIndexes: file_proto_task_proto_depIdxs,
		EnumInfos:         file_proto_task_proto_enumTypes,
		MessageInfos:      file_proto_task_proto_msgTypes,
	}.Build()
	File_proto_task_proto = out.File
	file_proto_task_proto_goTypes = nil
	file_proto_task_proto_depIdxs = nil
}
