// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/clientServer.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_MOVIES  FileType = 0
	FileType_CREDITS FileType = 1
	FileType_RATINGS FileType = 2
	FileType_EOF     FileType = 3
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "MOVIES",
		1: "CREDITS",
		2: "RATINGS",
		3: "EOF",
	}
	FileType_value = map[string]int32{
		"MOVIES":  0,
		"CREDITS": 1,
		"RATINGS": 2,
		"EOF":     3,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clientServer_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_proto_clientServer_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_proto_clientServer_proto_rawDescGZIP(), []int{0}
}

type MessageResponseType int32

const (
	MessageResponseType_UNKNOWN          MessageResponseType = 0
	MessageResponseType_BATCH_RESPONSE   MessageResponseType = 1
	MessageResponseType_REQUEST_RESPONSE MessageResponseType = 2
	MessageResponseType_ERROR            MessageResponseType = 3
)

// Enum value maps for MessageResponseType.
var (
	MessageResponseType_name = map[int32]string{
		0: "UNKNOWN",
		1: "BATCH_RESPONSE",
		2: "REQUEST_RESPONSE",
		3: "ERROR",
	}
	MessageResponseType_value = map[string]int32{
		"UNKNOWN":          0,
		"BATCH_RESPONSE":   1,
		"REQUEST_RESPONSE": 2,
		"ERROR":            3,
	}
)

func (x MessageResponseType) Enum() *MessageResponseType {
	p := new(MessageResponseType)
	*p = x
	return p
}

func (x MessageResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clientServer_proto_enumTypes[1].Descriptor()
}

func (MessageResponseType) Type() protoreflect.EnumType {
	return &file_proto_clientServer_proto_enumTypes[1]
}

func (x MessageResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageResponseType.Descriptor instead.
func (MessageResponseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_clientServer_proto_rawDescGZIP(), []int{1}
}

type RequestResponse_RequestType int32

const (
	RequestResponse_QUERY_1 RequestResponse_RequestType = 0
	RequestResponse_QUERY_2 RequestResponse_RequestType = 1
	RequestResponse_QUERY_3 RequestResponse_RequestType = 2
	RequestResponse_QUERY_4 RequestResponse_RequestType = 3
	RequestResponse_QUERY_5 RequestResponse_RequestType = 4
)

// Enum value maps for RequestResponse_RequestType.
var (
	RequestResponse_RequestType_name = map[int32]string{
		0: "QUERY_1",
		1: "QUERY_2",
		2: "QUERY_3",
		3: "QUERY_4",
		4: "QUERY_5",
	}
	RequestResponse_RequestType_value = map[string]int32{
		"QUERY_1": 0,
		"QUERY_2": 1,
		"QUERY_3": 2,
		"QUERY_4": 3,
		"QUERY_5": 4,
	}
)

func (x RequestResponse_RequestType) Enum() *RequestResponse_RequestType {
	p := new(RequestResponse_RequestType)
	*p = x
	return p
}

func (x RequestResponse_RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestResponse_RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clientServer_proto_enumTypes[2].Descriptor()
}

func (RequestResponse_RequestType) Type() protoreflect.EnumType {
	return &file_proto_clientServer_proto_enumTypes[2]
}

func (x RequestResponse_RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestResponse_RequestType.Descriptor instead.
func (RequestResponse_RequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_clientServer_proto_rawDescGZIP(), []int{3, 0}
}

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FileType               `protobuf:"varint,1,opt,name=type,proto3,enum=FileType" json:"type,omitempty"`
	Data          []*Batch_Row           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_clientServer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientServer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_clientServer_proto_rawDescGZIP(), []int{0}
}

func (x *Batch) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_MOVIES
}

func (x *Batch) GetData() []*Batch_Row {
	if x != nil {
		return x.Data
	}
	return nil
}

type GenericMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageResponseType    `protobuf:"varint,1,opt,name=type,proto3,enum=MessageResponseType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericMessageResponse) Reset() {
	*x = GenericMessageResponse{}
	mi := &file_proto_clientServer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericMessageResponse) ProtoMessage() {}

func (x *GenericMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientServer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericMessageResponse.ProtoReflect.Descriptor instead.
func (*GenericMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientServer_proto_rawDescGZIP(), []int{1}
}

func (x *GenericMessageResponse) GetType() MessageResponseType {
	if x != nil {
		return x.Type
	}
	return MessageResponseType_UNKNOWN
}

func (x *GenericMessageResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_proto_clientServer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientServer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientServer_proto_rawDescGZIP(), []int{2}
}

func (x *BatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          RequestResponse_RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=RequestResponse_RequestType" json:"type,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestResponse) Reset() {
	*x = RequestResponse{}
	mi := &file_proto_clientServer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResponse) ProtoMessage() {}

func (x *RequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientServer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResponse.ProtoReflect.Descriptor instead.
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientServer_proto_rawDescGZIP(), []int{3}
}

func (x *RequestResponse) GetType() RequestResponse_RequestType {
	if x != nil {
		return x.Type
	}
	return RequestResponse_QUERY_1
}

func (x *RequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Batch_Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch_Row) Reset() {
	*x = Batch_Row{}
	mi := &file_proto_clientServer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch_Row) ProtoMessage() {}

func (x *Batch_Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientServer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch_Row.ProtoReflect.Descriptor instead.
func (*Batch_Row) Descriptor() ([]byte, []int) {
	return file_proto_clientServer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Batch_Row) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_proto_clientServer_proto protoreflect.FileDescriptor

const file_proto_clientServer_proto_rawDesc = "" +
	"\n" +
	"\x18proto/clientServer.proto\"a\n" +
	"\x05Batch\x12\x1d\n" +
	"\x04type\x18\x01 \x01(\x0e2\t.FileTypeR\x04type\x12\x1e\n" +
	"\x04data\x18\x02 \x03(\v2\n" +
	".Batch.RowR\x04data\x1a\x19\n" +
	"\x03Row\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\\\n" +
	"\x16GenericMessageResponse\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.MessageResponseTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\")\n" +
	"\rBatchResponse\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xad\x01\n" +
	"\x0fRequestResponse\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.RequestResponse.RequestTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\vRequestType\x12\v\n" +
	"\aQUERY_1\x10\x00\x12\v\n" +
	"\aQUERY_2\x10\x01\x12\v\n" +
	"\aQUERY_3\x10\x02\x12\v\n" +
	"\aQUERY_4\x10\x03\x12\v\n" +
	"\aQUERY_5\x10\x04*9\n" +
	"\bFileType\x12\n" +
	"\n" +
	"\x06MOVIES\x10\x00\x12\v\n" +
	"\aCREDITS\x10\x01\x12\v\n" +
	"\aRATINGS\x10\x02\x12\a\n" +
	"\x03EOF\x10\x03*W\n" +
	"\x13MessageResponseType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eBATCH_RESPONSE\x10\x01\x12\x14\n" +
	"\x10REQUEST_RESPONSE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03B+Z)common/communication/client-comm/protocolb\x06proto3"

var (
	file_proto_clientServer_proto_rawDescOnce sync.Once
	file_proto_clientServer_proto_rawDescData []byte
)

func file_proto_clientServer_proto_rawDescGZIP() []byte {
	file_proto_clientServer_proto_rawDescOnce.Do(func() {
		file_proto_clientServer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clientServer_proto_rawDesc), len(file_proto_clientServer_proto_rawDesc)))
	})
	return file_proto_clientServer_proto_rawDescData
}

var file_proto_clientServer_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_clientServer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_clientServer_proto_goTypes = []any{
	(FileType)(0),                    // 0: FileType
	(MessageResponseType)(0),         // 1: MessageResponseType
	(RequestResponse_RequestType)(0), // 2: RequestResponse.RequestType
	(*Batch)(nil),                    // 3: Batch
	(*GenericMessageResponse)(nil),   // 4: GenericMessageResponse
	(*BatchResponse)(nil),            // 5: BatchResponse
	(*RequestResponse)(nil),          // 6: RequestResponse
	(*Batch_Row)(nil),                // 7: Batch.Row
}
var file_proto_clientServer_proto_depIdxs = []int32{
	0, // 0: Batch.type:type_name -> FileType
	7, // 1: Batch.data:type_name -> Batch.Row
	1, // 2: GenericMessageResponse.type:type_name -> MessageResponseType
	2, // 3: RequestResponse.type:type_name -> RequestResponse.RequestType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_clientServer_proto_init() }
func file_proto_clientServer_proto_init() {
	if File_proto_clientServer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clientServer_proto_rawDesc), len(file_proto_clientServer_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_clientServer_proto_goTypes,
		DependencyIndexes: file_proto_clientServer_proto_depIdxs,
		EnumInfos:         file_proto_clientServer_proto_enumTypes,
		MessageInfos:      file_proto_clientServer_proto_msgTypes,
	}.Build()
	File_proto_clientServer_proto = out.File
	file_proto_clientServer_proto_goTypes = nil
	file_proto_clientServer_proto_depIdxs = nil
}
