// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/messages/send-messages.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_MOVIES  FileType = 0
	FileType_CREDITS FileType = 1
	FileType_RATINGS FileType = 2
	FileType_EOF     FileType = 3
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "MOVIES",
		1: "CREDITS",
		2: "RATINGS",
		3: "EOF",
	}
	FileType_value = map[string]int32{
		"MOVIES":  0,
		"CREDITS": 1,
		"RATINGS": 2,
		"EOF":     3,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messages_send_messages_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_proto_messages_send_messages_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_proto_messages_send_messages_proto_rawDescGZIP(), []int{0}
}

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FileType               `protobuf:"varint,1,opt,name=type,proto3,enum=FileType" json:"type,omitempty"`
	Data          []*Batch_Row           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_messages_send_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_send_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_messages_send_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Batch) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_MOVIES
}

func (x *Batch) GetData() []*Batch_Row {
	if x != nil {
		return x.Data
	}
	return nil
}

type SyncMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	mi := &file_proto_messages_send_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_send_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_proto_messages_send_messages_proto_rawDescGZIP(), []int{1}
}

type SendMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*SendMessage_Batch
	//	*SendMessage_Sync
	Message       isSendMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_proto_messages_send_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_send_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_proto_messages_send_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessage) GetMessage() isSendMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessage) GetBatch() *Batch {
	if x != nil {
		if x, ok := x.Message.(*SendMessage_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *SendMessage) GetSync() *SyncMessage {
	if x != nil {
		if x, ok := x.Message.(*SendMessage_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

type isSendMessage_Message interface {
	isSendMessage_Message()
}

type SendMessage_Batch struct {
	Batch *Batch `protobuf:"bytes,1,opt,name=batch,proto3,oneof"`
}

type SendMessage_Sync struct {
	Sync *SyncMessage `protobuf:"bytes,2,opt,name=sync,proto3,oneof"`
}

func (*SendMessage_Batch) isSendMessage_Message() {}

func (*SendMessage_Sync) isSendMessage_Message() {}

type Batch_Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch_Row) Reset() {
	*x = Batch_Row{}
	mi := &file_proto_messages_send_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch_Row) ProtoMessage() {}

func (x *Batch_Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_send_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch_Row.ProtoReflect.Descriptor instead.
func (*Batch_Row) Descriptor() ([]byte, []int) {
	return file_proto_messages_send_messages_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Batch_Row) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_proto_messages_send_messages_proto protoreflect.FileDescriptor

const file_proto_messages_send_messages_proto_rawDesc = "" +
	"\n" +
	"\"proto/messages/send-messages.proto\"a\n" +
	"\x05Batch\x12\x1d\n" +
	"\x04type\x18\x01 \x01(\x0e2\t.FileTypeR\x04type\x12\x1e\n" +
	"\x04data\x18\x02 \x03(\v2\n" +
	".Batch.RowR\x04data\x1a\x19\n" +
	"\x03Row\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\r\n" +
	"\vSyncMessage\"\\\n" +
	"\vSendMessage\x12\x1e\n" +
	"\x05batch\x18\x01 \x01(\v2\x06.BatchH\x00R\x05batch\x12\"\n" +
	"\x04sync\x18\x02 \x01(\v2\f.SyncMessageH\x00R\x04syncB\t\n" +
	"\amessage*9\n" +
	"\bFileType\x12\n" +
	"\n" +
	"\x06MOVIES\x10\x00\x12\v\n" +
	"\aCREDITS\x10\x01\x12\v\n" +
	"\aRATINGS\x10\x02\x12\a\n" +
	"\x03EOF\x10\x03B+Z)common/communication/client-comm/protocolb\x06proto3"

var (
	file_proto_messages_send_messages_proto_rawDescOnce sync.Once
	file_proto_messages_send_messages_proto_rawDescData []byte
)

func file_proto_messages_send_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_send_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_send_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_send_messages_proto_rawDesc), len(file_proto_messages_send_messages_proto_rawDesc)))
	})
	return file_proto_messages_send_messages_proto_rawDescData
}

var file_proto_messages_send_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_messages_send_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_messages_send_messages_proto_goTypes = []any{
	(FileType)(0),       // 0: FileType
	(*Batch)(nil),       // 1: Batch
	(*SyncMessage)(nil), // 2: SyncMessage
	(*SendMessage)(nil), // 3: SendMessage
	(*Batch_Row)(nil),   // 4: Batch.Row
}
var file_proto_messages_send_messages_proto_depIdxs = []int32{
	0, // 0: Batch.type:type_name -> FileType
	4, // 1: Batch.data:type_name -> Batch.Row
	1, // 2: SendMessage.batch:type_name -> Batch
	2, // 3: SendMessage.sync:type_name -> SyncMessage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_messages_send_messages_proto_init() }
func file_proto_messages_send_messages_proto_init() {
	if File_proto_messages_send_messages_proto != nil {
		return
	}
	file_proto_messages_send_messages_proto_msgTypes[2].OneofWrappers = []any{
		(*SendMessage_Batch)(nil),
		(*SendMessage_Sync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_send_messages_proto_rawDesc), len(file_proto_messages_send_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_send_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_send_messages_proto_depIdxs,
		EnumInfos:         file_proto_messages_send_messages_proto_enumTypes,
		MessageInfos:      file_proto_messages_send_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_send_messages_proto = out.File
	file_proto_messages_send_messages_proto_goTypes = nil
	file_proto_messages_send_messages_proto_depIdxs = nil
}
